### ISSUE TITLE
Need to add section for Contributors to Note

### ISSUE THREAD

**Issue by clapierre** [w3c/dpub-accessibility#11]
In addition to the Participants in this TF, we should add a section to acknowledge those who helped us with this note (Invited Experts etc..)

IE:
Peter Krautzberger
Romain Deltour
Jean Kaplansky 
Matt Garrish

Others I am forgetting?

**Comment by TzviyaSiegman** [comment]
I think we should also thank Michael Cooper, Alistair Campbell, and Avneesh
Singh

On Mon, Mar 21, 2016 at 11:59 AM, Charles LaPierre <notifications@github.com

**Comment by clapierre** [comment]
Agreed!

**Comment by clapierre** [comment]
Renamed Table from A11Y TF Members to Contributors and added the afore mentioned contributors in alphabetical order.
