### ISSUE TITLE
Add references to PDF & PDF/UA in Section C

### ISSUE THREAD

**Issue by lrosenthol** [w3c/dpub-accessibility#20]
PDF is a key part of the Open Web Platform and certainly the most popular format used in digital publishing today.  It is the second most used media type on the web, behind HTML, and a normatively referenced format in the HTML5 specification.  
There also exists very clear guidance from WCAG on the using PDF in a conforming manner (https://www.w3.org/TR/2014/NOTE-WCAG20-TECHS-20140408/pdf.html).  In addition, there exists and entire international standard (ISO 14289-1, PDF/UA, http://www.iso.org/iso/home/store/catalogue_ics/catalogue_detail_ics.htm?csnumber=64599) that addresses the accessibility requirements of PDF - and has been adopted (or will be shortly) by a variety of countries around the world. 
It would be negligent to talk about digital publishing without reference to it.

I am happy to connect this group with ISO TC 171/SC 2/WG9 where the PDF/UA work is done to help in drafting useful text.

**Comment by iherman** [comment]
> On 18 Apr 2016, at 22:45, lrosenthol notifications@github.com wrote:
> 
> PDF is a key part of the Open Web Platform and certainly the most popular format used in digital publishing today. It is the second most used media type on the web, behind HTML, and a normatively referenced format in the HTML5 specification.
> 
> There also exists very clear guidance from WCAG on the using PDF in a conforming manner (https://www.w3.org/TR/2014/NOTE-WCAG20-TECHS-20140408/pdf.html https://www.w3.org/TR/2014/NOTE-WCAG20-TECHS-20140408/pdf.html). In addition, there exists and entire international standard (ISO 14289-1, PDF/UA, http://www.iso.org/iso/home/store/catalogue_ics/catalogue_detail_ics.htm?csnumber=64599 http://www.iso.org/iso/home/store/catalogue_ics/catalogue_detail_ics.htm?csnumber=64599) that addresses the accessibility requirements of PDF - and has been adopted (or will be shortly) by a variety of countries around the world.
> It would be negligent to talk about digital publishing without reference to it.
> 
> I am happy to connect this group with ISO TC 171/SC 2/WG9 where the PDF/UA work is done to help in drafting useful text.

What I do not know (and I am really not an expert in the area) whether digital publishing raises any specific issues related to PDF that are not covered by the aforementioned Note or the note in the making….

**Comment by lrosenthol** [comment]
> What I do not know (and I am really not an expert in the area) whether digital publishing raises any specific issues related to PDF that are not covered by the aforementioned Note or the note in the making….

Digital Publishing covers the use of the Open Web Platform (all parts) to delivery digitally authored and delivered content for various use cases.  As such, I can't see how PDF would not be included in that.
Additionally, there are a number of items in this particular document (such as multi-document navigation) which isn't addressed by WCAG (or PDF/UA) and is relevant for any publication type - or even more interestingly, a multi-format publication or collection of same.

**Comment by clapierre** [comment]
Leonard had some edits I missed
