### ISSUE TITLE
Remove Section "Work in Progress"

### ISSUE THREAD

**Issue by clapierre** [w3c/dpub-accessibility#21]
This is a work in progress. No section should be considered final, and the absence of any content does not imply that such content is out of scope, or may not appear in the future. If you feel something should be covered here, tell us! @@@T.B.D.@@@

**Comment by clapierre** [comment]
Ivan, can you comment on how we we should change this to comply with W3C verbiage for about to be published Note.

**Comment by iherman** [comment]
I think the text is fine as it is; maybe the last sentence ("if you feel...") can be removed, because it is covered by the boilerplate that respec generates.

**Comment by clapierre** [comment]
I assume the @@@TDB@@@ was to be taken out as well right?  that isn't a ReSpec directive was it?

**Comment by iherman** [comment]
> On 25 Apr 2016, at 16:31, Charles LaPierre notifications@github.com wrote:
> 
> I assume the @@@TDB https://github.com/TDB@@@ was to be taken out as well right? that isn't a ReSpec directive was it?

Yep

---

Ivan Herman, W3C 
Digital Publishing Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704
