### ISSUE TITLE
Consider a new Name for our Note

### ISSUE THREAD

**Issue by clapierre** [w3c/dpub-accessibility#22]
Currently our Note is named "Digital Publishing Accessibility Note"
Should we consider a different name, maybe one more in line with what this Note is trying to showcase?
I am fine leaving this just thought I would bring this up before we publish.

**Comment by TzviyaSiegman** [comment]
What about "Digital Publishing Accessibility Gap Assessment"?

**Comment by mgylling** [comment]
Maybe Analysis instead of Assessment? The latter makes me think of QTI... 🐙

**Comment by iherman** [comment]
Combining the two…

"Digital Publishing Accessibility Analysis"?

(I am not sure emphasizing the 'Gap' up front is a good idea.)

Ivan

> On 19 Apr 2016, at 20:56, Markus Gylling notifications@github.com wrote:
> 
> Maybe Analysis instead of Assessment? The latter makes me think of QTI... 🐙
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub https://github.com/w3c/dpub-accessibility/issues/22#issuecomment-212068089

---

Ivan Herman, W3C
Digital Publishing Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by clapierre** [comment]
I vote for Ivan's!

**Comment by clapierre** [comment]
Per our A11Y meeting discussion we will change this to
"Digital Publishing and Accessibility in W3C Documents"
And discuss at DPUB meeting

**Comment by mgylling** [comment]
I note that the title reference in the first sentence of the abstract was not updated to reflect the new name.
