### ISSUE TITLE
Correct use of class='appendix'

### ISSUE THREAD

**Issue by pkra** [w3c/dpub-accessibility#6]
It seems `class='appendix'` is used inconsistently. The overall section element for the appendix has it, and some subsections have it as well. I'm guessing it's only needed on the higher level section. Could someone confirm? Then I'd fix it up.

**Comment by clapierre** [comment]
From Ivan:
I believe Peter is right: setting the appendix class on a top section is enough, respec will automatically propagate this 'downwards'. In fact, whether you set the class on subsection or not does not affect the output at all… but it is better to be consistent within one document indeed.

Cheers

Ivan

**Comment by clapierre** [comment]
Peter if you wouldn't mind taking a look to see if this looks compliant now.
Thanks

**Comment by pkra** [comment]
LGTM. Fixed by https://github.com/w3c/dpub-accessibility/commit/72aa697ba476ffe5ae6889cdd81d17f036877339
